import { ref, } from 'vue'

interface data {
    placeholder: string,
    minInputLength: number,
    hint: boolean
}
export let options = ref<data>({
    placeholder: 'States of USA',
    minInputLength: 1,
    hint: false
})
export let listFiltered = ref<string[]>([])
export let list = ref<string[]>(['alabama',
    'alaska',
    'arizona',
    'arkansas',
    'california',
    'colorado',
    'connecticut',
    'delaware',
    'florida',
    'georgia',
    'hawaii',
    'idaho',
    'illinois',
    'indiana',
    'iowa',
    'kansas',
    'kentucky',
    'louisiana',
    'maine',
    'maryland',
    'massachusetts',
    'michigan',
    'minnesota',
    'mississippi',
    'missouri',
    'montana',
    'nebraska',
    'nevada',
    'new hampshire',
    'new jersey',
    'new mexico',
    'new york',
    'north carolina',
    'north dakota',
    'ohio',
    'oklahoma',
    'oregon',
    'pennsylvania',
    'rhode island',
    'south carolina',
    'south dakota',
    'tennessee',
    'texas',
    'utah',
    'vermont',
    'virginia',
    'washington',
    'west virginia',
    'wisconsin',
    'wyoming',
])
export let lists = ref<string[]>(['West Side Story - 1961',
    'Lawrence of Arabia - 1962',
    'Tom Jones - 1963',
    'My Fair Lady - 1964',
    'The Sound of Music - 1965',
    'A Man for All Seasons - 1966',
    'In the Heat of the Night - 1967',
    'Oliver! - 1968',
    'Midnight Cowboy - 1969',
    'Patton - 1970',
    'The French Connection - 1971',
    'The Godfather - 1972',
    'The Sting - 1973',
    'The Godfather Part II - 1974',
    'One Flew over the Cuckoo"s Nest - 1975',
    'Rocky - 1976',
    'Annie Hall - 1978',
    'The Deer Hunter - 1979',
    'Kramer vs. Kramer - 1980',
    'Ordinary People - 1981',
    'Chariots of Fire - 1982',
    'Gandhi - 1983',
    'Terms of Endearment - 1984',
    'Amadeus - 1985',
    'Out of Africa - 1986',
    'Platoon - 1987',
    'The Last Emperor - 1988',
    'Rain Man - 1989',
    'Driving Miss Daisy - 1990',
    'Dances With Wolves - 1991',
    'The Silence of the Lambs - 1992',
    'Unforgiven - 1993',
    'Schindler’s List - 1994',
    'Forrest Gump - 1995',
    'Braveheart - 1996',
    'The English Patient - 1997',
    'Titanic - 1998',
    'Shakespeare in Love - 1999',
    'American Beauty - 2000',
    'Gladiator - 2001',
    'A Beautiful Mind - 2002',
    'Chicago - 2003',
    'The Lord of the Rings: The Return of the King - 2004',
    'Million Dollar Baby - 2005',
    'Crash - 2005',
    'The Departed - 2006',
    'No Country for Old Men - 2007',
    'Slumdog Millionaire - 2008',
    'The Hurt Locker - 2009',
    'The King"s Speech - 2010',
    'The Artist - 2011',
    'Argo - 2012',
])
export let multiple = ref<string[]>(["Boston Celtics", "Dallas Mavericks", "Brooklyn Nets", "Houston Rockets", "New York Knicks", "Memphis Grizzlies", "Philadelphia 76ers", "New Orleans Hornets", "Toronto Raptors", "San Antonio Spurs", "Chicago Bulls", "Denver Nuggets", "Cleveland Cavaliers", "Minnesota Timberwolves", "Detroit Pistons", "Portland Trail Blazers", "Indiana Pacers", "Oklahoma City Thunder", "Milwaukee Bucks", "Utah Jazz", "Atlanta Hawks", "Golden State Warriors", "Charlotte Bobcats", "Los Angeles Clippers", "Miami Heat", "Los Angeles Lakers", "Orlando Magic", "Phoenix Suns", "Washington Wizards", "Sacramento Kings", "New Jersey Devils", "New York Islanders", "New York Rangers", "Philadelphia Flyers", "Pittsburgh Penguins", "Chicago Blackhawks", "Columbus Blue Jackets", "Detroit Red Wings", "Nashville Predators", "St. Louis Blues", "Boston Bruins", "Buffalo Sabres", "Montreal Canadiens", "Ottawa Senators", "Toronto Maple Leafs", "Calgary Flames", "Colorado Avalanche", "Edmonton Oilers", "Minnesota Wild", "Vancouver Canucks", "Carolina Hurricanes", "Florida Panthers", "Tampa Bay Lightning", "Washington Capitals", "Winnipeg Jets", "Anaheim Ducks", "Dallas Stars", "Los Angeles Kings", "Phoenix Coyotes", "San Jose Sharks"]
)
export let scroll = ref<string[]>(["Andorra", "United Arab Emirates", "Afghanistan", "Antigua and Barbuda", "Anguilla", "Albania", "Armenia", "Angola", "Antarctica", "Argentina", "American Samoa", "Austria", "Australia", "Aruba", "Åland", "Azerbaijan", "Bosnia and Herzegovina", "Barbados", "Bangladesh", "Belgium", "Burkina Faso", "Bulgaria", "Bahrain", "Burundi", "Benin", "Saint Barthélemy", "Bermuda", "Brunei", "Bolivia", "Bonaire", "Brazil", "Bahamas", "Bhutan", "Bouvet Island", "Botswana", "Belarus", "Belize", "Canada", "Cocos [Keeling] Islands", "Congo", "Central African Republic", "Republic of the Congo", "Switzerland", "Ivory Coast", "Cook Islands", "Chile", "Cameroon", "China", "Colombia", "Costa Rica", "Enzo", "Cape Verde", "Curacao", "Christmas Island", "Cyprus", "Czechia", "Germany", "Djibouti", "Denmark", "Dominica", "Dominican Republic", "Algeria", "Ecuador", "Estonia", "Egypt", "Western Sahara", "Eritrea", "Spain", "Ethiopia", "Finland", "Fiji", "Falkland Islands", "Micronesia", "Faroe Islands", "France", "Gabon", "United Kingdom", "Grenada", "Georgia", "French Guiana", "Guernsey", "Ghana", "Gibraltar", "Greenland", "Gambia", "Guinea", "Guadeloupe", "Equatorial Guinea", "Greece", "South Georgia and the South Sandwich Islands", "Guatemala", "Guam", "Guinea-Bissau", "Guyana", "Hong Kong", "Heard Island and McDonald Islands", "Honduras", "Croatia", "Haiti", "Hungary", "Indonesia", "Ireland", "Israel", "Isle of Man", "India", "British Indian Ocean Territory", "Iraq", "Iran", "Iceland", "Italy", "Jersey", "Jamaica", "Jordan", "Japan", "Kenya", "Kyrgyzstan", "Cambodia", "Kiribati", "Comoros", "Saint Kitts and Nevis", "North Korea", "South Korea", "Kuwait", "Cayman Islands", "Kazakhstan", "Laos", "Lebanon", "Saint Lucia", "Liechtenstein", "Sri Lanka", "Liberia", "Lesotho", "Lithuania", "Luxembourg", "Latvia", "Libya", "Morocco", "Monaco", "Moldova", "Montenegro", "Saint Martin", "Madagascar", "Marshall Islands", "Macedonia", "Mali", "Myanmar [Burma]", "Mongolia", "Macao", "Northern Mariana Islands", "Martinique", "Mauritania", "Montserrat", "Malta", "Mauritius", "Maldives", "Malawi", "Mexico", "Malaysia", "Mozambique", "Namibia", "New Caledonia", "Niger", "Norfolk Island", "Nigeria", "Nicaragua", "Netherlands", "Norway", "Nepal", "Nauru", "Niue", "New Zealand", "Oman", "Panama", "Peru", "French Polynesia", "Papua New Guinea", "Philippines", "Pakistan", "Poland", "Saint Pierre and Miquelon", "Pitcairn Islands", "Puerto Rico", "Palestine", "Portugal", "Palau", "Paraguay", "Qatar", "Réunion", "Romania", "Serbia", "Russia", "Rwanda", "Saudi Arabia", "Solomon Islands", "Seychelles", "Sudan", "Sweden", "Singapore", "Saint Helena", "Slovenia", "Svalbard and Jan Mayen", "Slovakia", "Sierra Leone", "San Marino", "Senegal", "Somalia", "Suriname", "South Sudan", "São Tomé and Príncipe", "El Salvador", "Sint Maarten", "Syria", "Swaziland", "Turks and Caicos Islands", "Chad", "French Southern Territories", "Togo", "Thailand", "Tajikistan", "Tokelau", "East Timor", "Turkmenistan", "Tunisia", "Tonga", "Turkey", "Trinidad and Tobago", "Tuvalu", "Taiwan", "Tanzania", "Ukraine", "Uganda", "U.S. Minor Outlying Islands", "United States", "Uruguay", "Uzbekistan", "Vatican City", "Saint Vincent and the Grenadines", "Venezuela", "British Virgin Islands", "U.S. Virgin Islands", "Vietnam", "Vanuatu", "Wallis and Futuna", "Samoa", "Kosovo", "Yemen", "Mayotte", "South Africa", "Zambia", "Zimbabwe"
])
export let remote = ref<string[]>(['West Side Story',
    'Lawrence of Arabia',
    'Tom Jones',
    'My Fair Lady',
    'The Sound of Music',
    'A Man for All Seasons',
    'In the Heat of the Night',
    'Oliver!',
    'Midnight Cowboy',
    'Patton',
    'The French Connection',
    'The Godfather',
    'The Sting',
    'The Godfather Part II',
    'One Flew over the Cuckoo"s Nest',
    'Rocky',
    'Annie Hall',
    'The Deer Hunter',
    'Kramer vs. Kramer',
    'Ordinary People',
    'Chariots of Fire',
    'Gandhi',
    'Terms of Endearment',
    'Amadeus',
    'Out of Africa',
    'Platoon',
    'The Last Emperor',
    'Rain Man',
    'Driving Miss Daisy',
    'Dances With Wolves',
    'The Silence of the Lambs',
    'Unforgiven',
    'Schindler’s List',
    'Forrest Gump',
    'Braveheart',
    'The English Patient',
    'Titanic',
    'Shakespeare in Love',
    'American Beauty',
    'Gladiator',
    'A Beautiful Mind',
    'Chicago',
    'The Lord of the Rings: The Return of the King',
    'Million Dollar Baby',
    'Crash',
    'The Departed',
    'No Country for Old Men',
    'Slumdog Millionaire',
    'The Hurt Locker',
    'The King"s Speech',
    'The Artist',
    'Argo',

])


export function selectItem(item: string) {

}
export function onInput(event: { items: string[] }) {

    listFiltered.value = event.items;
}
export function onBlur(event: { items: string[] }) {

    listFiltered.value = event.items;
}
